# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjournal',
            name='real_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
