# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_userjournal_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjournal',
            name='process',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userjournal',
            name='time_consumed',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='userjournal',
            name='usr_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
